[tool.poetry]
name = "intervals"
version = "0.1.0"
description = "crim intervals package"
authors = ["Richard Freedman <rfreedma@haverford.edu>"]
license = "creative commons"
packages = [
    { include = "*.py" },
]

[tool.poetry.dependencies]
python = ">=3.7.1,<4.0"
altair = "4.1.0"
certifi = "2020.12.5"
chardet = "^4.0.0"
h11 = "0.12.0"
httpcore = "0.13.2"
httpx = "0.18.1"
idna = "3.1"
ipywidgets = "7.6.3"
joblib = "1.0.1"
lxml = "4.6.3"
more-itertools = "8.7.0"
music21 = "7.1.0"
numpy = "1.20.2"
pandas = "1.2.4"
pyvis = "0.1.9"
python-dateutil = "^2.8.2"
pytz = "2021.1"
rfc3986 = "1.4.0"
six = "1.15.0"
sniffio = "^1.2.0"
textdistance = "4.2.1"
XlsxWriter = "3.0.2"
webcolors = "1.11.1"

[tool.poetry.dev-dependencies]

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
